Rails.application.routes.draw do
  get("/flexible/square/:num", {:controller => "calculations", :action => "flex_square"})
  get("/flexible/square_root/:num", {:controller => "calculations", :action => "flex_root"})
  get("/flexible/payment/:int/:term/:princip", {:controller => "calculations", :action => "flex_pmt"})
  get("/flexible/random/:min/:max", {:controller => "calculations", :action => "flex_rand"})
  get("/square/new", {:controller => "calculations", :action => "square_form"})
  get("/square/results", {:controller => "calculations", :action => "square_results"})
  get("/square_root/new", {:controller => "calculations", :action => "square_root_form"})
  get("/square_root/results", {:controller => "calculations", :action => "square_root_results"})
  get("/payment/new", {:controller => "calculations", :action => "pmt_form"})
  get("/payment/results", {:controller => "calculations", :action => "pmt_results"})
  get("/random/new", {:controller => "calculations", :action => "rand_form"})
  get("/random/results", {:controller => "calculations", :action => "rand_results"})
  get("/word_count/new", {:controller => "calculations", :action => "word_form"})
  get("/word_count/results", {:controller => "calculations", :action => "word_results"})
  get("/descriptive_stats/new", {:controller => "calculations", :action => "stats_form"})
  get("/descriptive_stats/results", {:controller => "calculations", :action => "stats_results"})
end
